name: "Update Submodule on Dispatch"

on:
  repository_dispatch:
    types: [submodule_updated]

jobs:
  update_submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'
        token: ${{ secrets.POST_TOKEN }}

    - name: Update submodule
      run: |
        git submodule update --remote --recursive
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add path/to/your/submodule
        git commit -m "Update submodule" || echo "No changes to commit"
        git push || echo "No changes to push"